import React from 'react'
import { 
  Eye, 
  Edit3, 
  Download, 
  Share2, 
  Trash2,
  ExternalLink,
  FileText,
  Clock,
  Calendar
} from 'lucide-react'

const NotePreview = ({ file, onClose, onExport }) => {
  if (!file) {
    return (
      <div className="card h-full min-h-[400px] flex items-center justify-center">
        <div className="text-center">
          <FileText className="w-12 h-12 text-text-muted mx-auto mb-3" />
          <p className="text-text-muted">Select a file to preview</p>
        </div>
      </div>
    )
  }
  
  // Mock markdown content
  const getMockContent = (fileName) => {
    const contents = {
      'Seaway Mall Block.md': `# Seaway Mall Block Deal

## Property Summary
- **Address:** 238 Ontario St, St. Catharines, ON
- **Asset Class:** Retail / Mixed-Use
- **Price:** $45,000,000
- **Size:** 425,000 SF
- **Cap Rate:** 6.2%

## Key Tenants
1. **Canadian Tire** - 85,000 SF (Anchor)
2. **Shoppers Drug Mart** - 15,000 SF
3. **CIBC** - 3,500 SF
4. **Various inline retail** - Remaining space

## Hot Money Matches

### 🔥 2650687 Ontario Ltd
- **Cash Position:** $15M (May 2025)
- **Match Score:** 92/100
- **Previous Purchase:** Thirty Rd, West Lincoln ($11.5M)
- **Contact:** Available via Property Shark

### 🔥 Turnberry Holdings Inc
- **Cash Position:** $9.8M (Jan 2025)
- **Match Score:** 88/100
- **Profile:** Active in Niagara region

## Recommended Action
1. Contact 2650687 Ontario Ltd within 48 hours
2. Prepare OM for qualified buyers
3. Schedule site visit

---
*Generated by BigDataClaw NERVE*
`,
      'Hot Money Q1 2025.md': `# Hot Money Analysis Q1 2025

## Executive Summary
Total tracked hot money: **$156M** across 23 entities in Niagara region.

## Top Hot Money Leads

| Entity | Cash Position | Sale Date | Location | Match Score |
|--------|--------------|-----------|----------|-------------|
| 2650687 Ontario Ltd | $15M | May 2025 | West Lincoln | 92 |
| Turnberry Holdings | $9.8M | Jan 2025 | Lincoln | 88 |
| 1863570 Ontario Inc | $7M | Jan 2025 | Pelham | 85 |
| Landtract Ltd | $5.6M | Feb 2025 | Grimsby | 82 |

## Geographic Distribution
- **West Lincoln:** 28% ($43M)
- **St. Catharines:** 22% ($34M)
- **Niagara Falls:** 18% ($28M)
- **Pelham:** 15% ($23M)
- **Other:** 17% ($28M)

## Asset Class Preferences
1. Industrial (45%)
2. Retail (30%)
3. Mixed-Use (15%)
4. Agricultural (10%)

---
*Last updated: March 27, 2025*
`,
    }
    
    return contents[fileName] || `# ${fileName}

This is a sample note from the Obsidian vault.

## Key Points
- Point 1
- Point 2
- Point 3

## Next Steps
1. Action item
2. Follow up
3. Close deal

---
*Created by BigDataClaw NERVE*
`
  }
  
  const content = getMockContent(file.name)
  
  // Simple markdown renderer (very basic)
  const renderMarkdown = (text) => {
    const lines = text.split('\n')
    return lines.map((line, i) => {
      // Headers
      if (line.startsWith('# ')) {
        return <h1 key={i} className="text-2xl font-bold text-text-primary mb-4">{line.slice(2)}</h1>
      }
      if (line.startsWith('## ')) {
        return <h2 key={i} className="text-xl font-semibold text-text-primary mt-6 mb-3">{line.slice(3)}</h2>
      }
      if (line.startsWith('### ')) {
        return <h3 key={i} className="text-lg font-semibold text-text-primary mt-4 mb-2">{line.slice(4)}</h3>
      }
      
      // Lists
      if (line.startsWith('- ')) {
        return <li key={i} className="ml-4 text-text-secondary">{renderInline(line.slice(2))}</li>
      }
      if (/^\d+\./.test(line)) {
        return <li key={i} className="ml-4 text-text-secondary">{renderInline(line.replace(/^\d+\./, ''))}</li>
      }
      
      // Table row
      if (line.startsWith('|')) {
        const cells = line.split('|').filter(c => c.trim())
        if (cells.length > 0 && !cells[0].includes('-')) {
          return (
            <tr key={i} className="border-b border-border-subtle">
              {cells.map((cell, j) => (
                <td key={j} className="py-2 px-3 text-sm text-text-secondary">{cell.trim()}</td>
              ))}
            </tr>
          )
        }
        return null
      }
      
      // Empty line
      if (line.trim() === '') {
        return <div key={i} className="h-2" />
      }
      
      // Horizontal rule
      if (line.startsWith('---')) {
        return <hr key={i} className="my-4 border-border-subtle" />
      }
      
      // Bold text (key-value pairs)
      if (line.startsWith('**') && line.includes(':**')) {
        const [key, ...value] = line.split(':**')
        return (
          <div key={i} className="my-1">
            <span className="font-semibold text-text-primary">{key.slice(2)}:</span>
            <span className="text-text-secondary">{value.join(':**').trim()}</span>
          </div>
        )
      }
      
      // Regular paragraph
      return <p key={i} className="text-text-secondary my-2">{renderInline(line)}</p>
    })
  }
  
  const renderInline = (text) => {
    // Bold
    let result = text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    // Emoji
    result = result.replace(/(🔥|💰|📍|✅|⚠️)/g, '<span class="text-lg">$1</span>')
    return <span dangerouslySetInnerHTML={{ __html: result }} />
  }
  
  return (
    <div className="card h-full flex flex-col max-h-[600px]">
      {/* Header */}
      <div className="p-4 border-b border-border-subtle">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <FileText className="w-5 h-5 text-accent-blue" />
            <div>
              <h3 className="font-semibold text-text-primary">{file.name}</h3>
              <div className="flex items-center gap-3 text-xs text-text-muted mt-0.5">
                <span className="flex items-center gap-1">
                  <Calendar className="w-3 h-3" />
                  Modified {file.modified}
                </span>
                <span className="flex items-center gap-1">
                  <Clock className="w-3 h-3" />
                  {file.size}
                </span>
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            <button className="p-2 rounded-lg hover:bg-bg-input text-text-secondary transition-colors" title="Edit">
              <Edit3 className="w-4 h-4" />
            </button>
            <button className="p-2 rounded-lg hover:bg-bg-input text-text-secondary transition-colors" title="Preview">
              <Eye className="w-4 h-4" />
            </button>
            <button 
              onClick={() => onExport?.(file)}
              className="p-2 rounded-lg hover:bg-bg-input text-text-secondary transition-colors"
              title="Export"
            >
              <Download className="w-4 h-4" />
            </button>
            <button className="p-2 rounded-lg hover:bg-bg-input text-text-secondary transition-colors" title="Share">
              <Share2 className="w-4 h-4" />
            </button>
            <button className="p-2 rounded-lg hover:bg-accent-red/20 text-text-secondary hover:text-accent-red transition-colors" title="Delete">
              <Trash2 className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
      
      {/* Content */}
      <div className="flex-1 overflow-y-auto scrollbar-thin p-6">
        <div className="prose prose-invert max-w-none">
          {renderMarkdown(content)}
        </div>
      </div>
      
      {/* Footer */}
      <div className="p-3 border-t border-border-subtle flex items-center justify-between">
        <div className="flex items-center gap-2">
          <button 
            onClick={() => onExport?.(file)}
            className="btn-primary py-1.5 px-3 text-sm flex items-center gap-2"
          >
            <Download className="w-4 h-4" />
            Export to Vault
          </button>
        </div>
        
        <button 
          onClick={onClose}
          className="text-sm text-text-secondary hover:text-text-primary transition-colors flex items-center gap-1"
        >
          Open in Obsidian
          <ExternalLink className="w-3 h-3" />
        </button>
      </div>
    </div>
  )
}

export default NotePreview
